manifest_version = 1

[module]
name = "Stable Horde"
id = "stable_horde"
description = "Generate images using the stable horde"
version = "2.0.4"
license = "GNU GPLv3"
authors = ["Fripe"]
requirements = [
    "aiohttp",
    "pydantic>=2.0",
    "aiofiles"
]
