# Your stable horde api key
# This will work if left as the default (0000000000), but should be changed to one obtained from the website
# https://stablehorde.net/
stable_horde_api_key = "0000000000"

# How many votes are needed for a generated image to be deleted, useful in case it happens to be NSFW
# Set to -1 to disable image deletion
required_deletion_votes = 2

# The maximum ammount of kudos a generation request can require
max_kudo_cost = 10.0

# THe time to wait inbetween fetching the generation status from the horde.
# Try keep this as high as possible as to not overwelm the horde with requests
time_between_updates = 6

# What ControlNet model to use, set to "random" for a random model
avatar_remix_controlnet_model = "fakescribbles"
